Interfaces:
    # Ensure that all settings in this file are consistent with the settings in the instrument's LIS configuration.
    Serial:
        # The ReceiverId should match the "Sender ID" field on the instrument's LIS configuration screen.
      - ReceiverId:    IMMULITE
        # The password can be empty, but it should always match the password field on the instrument's LIS configuration screen.
        # This string is compared to the password field of each received message header to verify the identity of the instrument.
        # It is also included in the message header for outgoing messages.
        # In accordance with the ASTM/CLSI standards, it is transmitted in plaintext.
        Password:
        # Provide the name of the serial port connected to the instrument.
        Portname:   COM4
        # Acceptable baud rate values include 1200, 2400, 4800, or 9600 (default). Some systems may also support 19200 or 38400.
        Baud:   9600 
        # Acceptable parity values include None (default), Even, or Odd.
        Parity: None
        # Data bits may be 5, 6, 7, or 8 (default).
        Databits:   8
        # Stop bits may be One (default), OnePointFive, or Two.
        Stopbits:   One
        # Handshake protocols are not included in the specification. Only the default value of None is recommended.
        Handshake:  None
        # UseLegacyFrameSize determines how long a single message frame can be -- anything longer will be split into intermediate frames. 
        # Set to true to use ASTM-1394 limit of 240 characters. Set to false to use CLSI-LIS2-A2 limit of 63,993 characters.
        UseLegacyFrameSize:  true
        # AutoSendOrders is the interval in milliseconds for checking the database for new order request messages to send.
        # A value of 0 disables automatically sending orders, and they will only be sent in response to a query message from the instrument.
        AutoSendOrders:   0

      ## Uncomment the following lines to add additional instruments with serial port connections.
      #- ReceiverId:    INSTRUMENT_NAME
      #  password:
      #  portname:   COM#
      #  baud:   19200
      #  parity: None
      #  databits:   8
      #  stopbits:   One
      #  handshake:  None
      #  UseLegacyFrameSize:  false
      #  AutoSendOrders:    false

    Tcp:
        # The ReceiverId should match the "Sender ID" field on the instrument's LIS configuration screen.
      - ReceiverId:         TESTING
        # The password can be empty, but it should always match the password field on the instrument's LIS configuration screen.
        # This string is compared to the password field of each received message header to verify the identity of the instrument.
        # It is also included in the message header for outgoing messages.
        # In accordance with the ASTM/CLSI standards, it is transmitted in plaintext.
        Password:           
        # UseLegacyFrameSize determines how long a single message frame can be -- anything longer will be split into intermediate frames. 
        # Set to true to use ASTM-1394 limit of 240 characters. Set to false to use CLSI-LIS2-A2 limit of 63,993 characters.
        UseLegacyFrameSize: false
        # The TCP port number used to communicate with the analyzer. 
        # The instrument may or may not allow the user to specify a number.
        # In any case, this value must match the setting on the instrument.
        Socket:             5678
        # AutoSendOrders is the interval in milliseconds for checking the database for new order request messages to send.
        # A value of 0 disables automatically sending orders, and they will only be sent in response to a query message from the instrument.
        AutoSendOrders:     0
 
# The following settings are used more generally by the program and are not instrument-specific. 
# Some of these settings are currently unused but planned for a future release.
ServiceConfig:
    # If records are to be stored in/retrieved from an external database, set to true; if using only internal SQLite database, set to false.
    # CURRENTLY UNSUPPORTED
    UseExternalDb:    true
    # The connection string used to connect to the database.
    ConnectionString:  Data Source=127.0.0.1\SQLExpress;Initial Catalog=LISDB;Integrated Security=True
    # The file path to the SQLite database file.
    # CURRENTLY UNSUPPORTED
    SqlitePath: 
    # When using both internal (SQLite) and external (MySQL, SQL Server, etc.) databases, 
    # DbPollInterval defines the interval in milliseconds for checking the two for differences and updating them accordingly.
    # CURRENTLY UNSUPPORTED
    DbPollInterval:
    # ListenHl7 determines whether to listen for HL7-type messages from other programs.
    # CURRENTLY UNSUPPORTED
    ListenHl7:     true
    # Hl7TcpPort is the port number on which to listen for HL7 messages if ListenHl7 is true.
    # CURRENTLY UNSUPPORTED
    Hl7TcpPort:   9876
    # Designation of the LIS for message header purposes.                                   
    # This includes the "Receiver ID" field for incoming messages as well as the "Sender Name or ID" field for sent messages.
    LisId: MasterAnalyzerHandler
    # OPTIONAL: The street address of the sender, which may contain street address, city, state, ZIP/postal code, and country code,
    # separated by delimiters ( ^ ). This is unlikely to ever be used by an instrument but is included here for standards compliance.
    Address:
    # OPTIONAL: A telephone number for voice communication with the sender. Again, unlikely to be useful in practice.
    Phone:

# The following settings are used to map the various message fields to their respective fields in database tables.
# CURRENTLY UNSUPPORTED
TableFieldMappings:
    PatientRecord:
        PAPID: 
        LAPID: 
        PID3: 
        PName: 
        MMName: 
        DOB: 
        PSex: 
        PRace: 
        PAddr: 
        Reserved: 
        PTelNo: 
        Attending: 
        Special1: 
        Special2: 
        PHeight: 
        PWeight: 
        PDiag: 
        PMeds: 
        PDiet: 
        PF1: 
        PF2: 
        AdmDates: 
        AdmStatus: 
        PLocation: 
        AltCodeNature: 
        AltCode: 
        PReligion: 
        PMarStatus: 
        PIsoStatus: 
        PLanguage: 
        HospService: 
        HospInst: 
        DoseCat: 
    
    OrderRecord:
        PRID: 
        SpecID: 
        InSpecID: 
        UTID: 
        OrderDate: 
        CollectDate: 
        CollEndTime: 
        CollVolume: 
        Collector: 
        ActCode: 
        DangerCode: 
        RelClinInfo: 
        SpecRecd: 
        SpecDesc: 
        OrdPhys: 
        PhysTelNo: 
        UF1: 
        UF2: 
        LF1: 
        LF2: 
        LastReported: 
        BillRef: 
        InSectID: 
        RepType: 
        Reserved: 
        SpecColLocation: 
        NosInfFlag: 
        SpecService: 
        SpecInst: 
    
    ResultRecord:
        ORID: 
        UTID: 
        Result: 
        Unit: 
        RefRange: 
        Abnormal: 
        AbNature: 
        ResStatus: 
        NormsChanged: 
        OpID: 
        TestStart: 
        TestEnd: 
        InstID: 
    
    CommentRecord:
        Source: 
        Text: 
        Type: 
    
    QueryRecord:
        StartRange: 
        EndRange: 
        UTID: 
        ReqLimNature: 
        ReqResBeginDT: 
        ReqResEndDT: 
        ReqPhysName: 
        ReqPhysTelNo: 
        UF1: 
        UF2: 
        ReqInfoStatus: 
    
    ScientificRecord:
        AnalMeth: 
        Instrument: 
        Reagents: 
        Units: 
        QC: 
        SpecDesc: 
        Reserved: 
        Container: 
        SpecID: 
        Analyte: 
        Result: 
        ResUnits: 
        CollectDT: 
        ResultDT: 
        AnalPreSteps: 
        PatDiag: 
        PatDOB: 
        PSex: 
        PRace: 